name: Build & Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Trigger only when changes are pushed to the main branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t deep0510/flight-price-api .

      - name: Push Docker Image
        run: docker push deep0510/flight-price-api