apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-price-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-price
  template:
    metadata:
      labels:
        app: flight-price
    spec:
      containers:
        - name: flight-price-container
          image: deep0510/flight-price-api:4e7330becfe0a4fcbee87d594004cfdc39b684a4
          ports:
            - containerPort: 8000