apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-price-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-price
  template:
    metadata:
      labels:
        app: flight-price
    spec:
      containers:
        - name: flight-price-container
          image: deep0510/flight-price-api:63c5bf5a4cdb1832e347388ea3b88bee97884eb9
          ports:
            - containerPort: 8000