apiVersion: v1
kind: Service
metadata:
  name: flight-price-service
spec:
  selector:
    app: flight-price
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007  # You can choose any free port between 30000–32767