apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: mlflow/mlflow:2.11.3  # replace with your image if custom built
        ports:
        - containerPort: 5000
        command: ["mlflow", "server"]
        args:
          - "--backend-store-uri=postgresql://airflow:airflow@postgres/airflow"
          - "--default-artifact-root=/mlruns"
          - "--host=0.0.0.0"
        volumeMounts:
          - mountPath: /mlruns
            name: mlruns
      volumes:
        - name: mlruns
          hostPath:
            path: /mlruns
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050